services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8501:8501"
      - "11434:11434"
    environment:
      - PYTHONUNBUFFERED=1
    command: /bin/sh -c "python database_operations.py && streamlit run app.py --server.fileWatcherType poll"
