services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8501:8501"
      - "11434:11434"
    environment:
      - PYTHONUNBUFFERED=1
    command: /bin/sh -c "python /app/database_operations.py && streamlit run /app/app.py --server.fileWatcherType poll"
